# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xci
# IP: The module: 'ex_synth_hls_ip_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xci
# IP: The module: 'ex_synth_hls_ip_reset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_hls_ip_reset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
