# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vcu_DT_top.xdc

# Block Designs: bd/vcu_DT_blk_design/vcu_DT_blk_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design || ORIG_REF_NAME==vcu_DT_blk_design} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_vga_core_0_0/vcu_DT_blk_design_vga_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_vga_core_0_0 || ORIG_REF_NAME==vcu_DT_blk_design_vga_core_0_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_xlconstant_0_0/vcu_DT_blk_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_xlconstant_0_0 || ORIG_REF_NAME==vcu_DT_blk_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_c_counter_binary_0_0/vcu_DT_blk_design_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_c_counter_binary_0_0 || ORIG_REF_NAME==vcu_DT_blk_design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_xlslice_0_0/vcu_DT_blk_design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_xlslice_0_0 || ORIG_REF_NAME==vcu_DT_blk_design_xlslice_0_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_xlslice_0_1/vcu_DT_blk_design_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_xlslice_0_1 || ORIG_REF_NAME==vcu_DT_blk_design_xlslice_0_1} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_xlslice_1_0/vcu_DT_blk_design_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_xlslice_1_0 || ORIG_REF_NAME==vcu_DT_blk_design_xlslice_1_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_xlslice_2_0/vcu_DT_blk_design_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_xlslice_2_0 || ORIG_REF_NAME==vcu_DT_blk_design_xlslice_2_0} -quiet] -quiet

# IP: bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_DT_blk_design_clk_wiz_0_3 || ORIG_REF_NAME==vcu_DT_blk_design_clk_wiz_0_3} -quiet] -quiet

# XDC: bd/vcu_DT_blk_design/vcu_DT_blk_design_ooc.xdc
