# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/ex_synth/ex_synth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth || ORIG_REF_NAME==ex_synth} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_hls_ip_reset_0 || ORIG_REF_NAME==ex_synth_hls_ip_reset_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_video_lock_monitor_0/ex_synth_video_lock_monitor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_video_lock_monitor_0 || ORIG_REF_NAME==ex_synth_video_lock_monitor_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_v_tc_0_0/ex_synth_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_v_tc_0_0 || ORIG_REF_NAME==ex_synth_v_tc_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_vid_out_0/ex_synth_vid_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_vid_out_0 || ORIG_REF_NAME==ex_synth_vid_out_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_v_frmbuf_rd_0_0/ex_synth_v_frmbuf_rd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_v_frmbuf_rd_0_0 || ORIG_REF_NAME==ex_synth_v_frmbuf_rd_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_mig_0/ex_synth_mig_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_mig_0 || ORIG_REF_NAME==ex_synth_mig_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_axi_mem_intercon_0/ex_synth_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_axi_mem_intercon_0 || ORIG_REF_NAME==ex_synth_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_rst_mig_200M_0/ex_synth_rst_mig_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_rst_mig_200M_0 || ORIG_REF_NAME==ex_synth_rst_mig_200M_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_clk_wiz_1_0/ex_synth_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_clk_wiz_1_0 || ORIG_REF_NAME==ex_synth_clk_wiz_1_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_100M_0/ex_synth_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ex_synth_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_150M_0/ex_synth_rst_clk_wiz_1_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_rst_clk_wiz_1_150M_0 || ORIG_REF_NAME==ex_synth_rst_clk_wiz_1_150M_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_200M_0/ex_synth_rst_clk_wiz_1_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_rst_clk_wiz_1_200M_0 || ORIG_REF_NAME==ex_synth_rst_clk_wiz_1_200M_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_processor_0/ex_synth_processor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_processor_0 || ORIG_REF_NAME==ex_synth_processor_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_processor_axi_intc_0/ex_synth_processor_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_processor_axi_intc_0 || ORIG_REF_NAME==ex_synth_processor_axi_intc_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_processor_axi_periph_0/ex_synth_processor_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_processor_axi_periph_0 || ORIG_REF_NAME==ex_synth_processor_axi_periph_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_dlmb_v10_0/ex_synth_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_dlmb_v10_0 || ORIG_REF_NAME==ex_synth_dlmb_v10_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_ilmb_v10_0/ex_synth_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_ilmb_v10_0 || ORIG_REF_NAME==ex_synth_ilmb_v10_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_dlmb_bram_if_cntlr_0/ex_synth_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ex_synth_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_ilmb_bram_if_cntlr_0/ex_synth_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ex_synth_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_lmb_bram_0/ex_synth_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_lmb_bram_0 || ORIG_REF_NAME==ex_synth_lmb_bram_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_mdm_1_0/ex_synth_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_mdm_1_0 || ORIG_REF_NAME==ex_synth_mdm_1_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xbar_2/ex_synth_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xbar_2 || ORIG_REF_NAME==ex_synth_xbar_2} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xbar_3/ex_synth_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xbar_3 || ORIG_REF_NAME==ex_synth_xbar_3} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_clk_wiz_0_0/ex_synth_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_clk_wiz_0_0 || ORIG_REF_NAME==ex_synth_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xlslice_0_0/ex_synth_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xlslice_0_0 || ORIG_REF_NAME==ex_synth_xlslice_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xlslice_0_1/ex_synth_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xlslice_0_1 || ORIG_REF_NAME==ex_synth_xlslice_0_1} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xlslice_1_0/ex_synth_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xlslice_1_0 || ORIG_REF_NAME==ex_synth_xlslice_1_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_axi_uartlite_0_0/ex_synth_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_axi_uartlite_0_0 || ORIG_REF_NAME==ex_synth_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_axi_quad_spi_0_0/ex_synth_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_axi_quad_spi_0_0 || ORIG_REF_NAME==ex_synth_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_xlconcat_0_0/ex_synth_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_xlconcat_0_0 || ORIG_REF_NAME==ex_synth_xlconcat_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_us_0/ex_synth_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_us_0 || ORIG_REF_NAME==ex_synth_auto_us_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_0/ex_synth_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_0 || ORIG_REF_NAME==ex_synth_auto_cc_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_us_1/ex_synth_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_us_1 || ORIG_REF_NAME==ex_synth_auto_us_1} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_1/ex_synth_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_1 || ORIG_REF_NAME==ex_synth_auto_cc_1} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_us_2/ex_synth_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_us_2 || ORIG_REF_NAME==ex_synth_auto_us_2} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_2/ex_synth_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_2 || ORIG_REF_NAME==ex_synth_auto_cc_2} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_3/ex_synth_auto_cc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_3 || ORIG_REF_NAME==ex_synth_auto_cc_3} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_4/ex_synth_auto_cc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_4 || ORIG_REF_NAME==ex_synth_auto_cc_4} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_5/ex_synth_auto_cc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_5 || ORIG_REF_NAME==ex_synth_auto_cc_5} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_6/ex_synth_auto_cc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_6 || ORIG_REF_NAME==ex_synth_auto_cc_6} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_7/ex_synth_auto_cc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_7 || ORIG_REF_NAME==ex_synth_auto_cc_7} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_8/ex_synth_auto_cc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_8 || ORIG_REF_NAME==ex_synth_auto_cc_8} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_auto_cc_9 || ORIG_REF_NAME==ex_synth_auto_cc_9} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_axi_ethernetlite_0_0/ex_synth_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_axi_ethernetlite_0_0 || ORIG_REF_NAME==ex_synth_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/ex_synth/ip/ex_synth_axi_timer_0_0/ex_synth_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_synth_axi_timer_0_0 || ORIG_REF_NAME==ex_synth_axi_timer_0_0} -quiet] -quiet

# XDC: bd/ex_synth/ex_synth_ooc.xdc
