# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.cache/wt [current_project]
set_property parent.project_path /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/rwegter/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/hdl/ex_synth_wrapper.v
add_files /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ex_synth.bd
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_hls_ip_reset_0/ex_synth_hls_ip_reset_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_video_lock_monitor_0/ex_synth_video_lock_monitor_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_video_lock_monitor_0/ex_synth_video_lock_monitor_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_video_lock_monitor_0/ex_synth_video_lock_monitor_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_v_tc_0_0/ex_synth_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_v_tc_0_0/ex_synth_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_vid_out_0/ex_synth_vid_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_vid_out_0/ex_synth_vid_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_v_frmbuf_rd_0_0/ex_synth_v_frmbuf_rd_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_v_frmbuf_rd_0_0/ex_synth_v_frmbuf_rd_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_mig_0/ex_synth_mig_0/user_design/constraints/ex_synth_mig_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_mig_0/ex_synth_mig_0/user_design/constraints/ex_synth_mig_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_mig_0/ex_synth_mig_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_mig_200M_0/ex_synth_rst_mig_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_mig_200M_0/ex_synth_rst_mig_200M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_mig_200M_0/ex_synth_rst_mig_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_1_0/ex_synth_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_1_0/ex_synth_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_1_0/ex_synth_clk_wiz_1_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_1_0/ex_synth_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_100M_0/ex_synth_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_100M_0/ex_synth_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_100M_0/ex_synth_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_150M_0/ex_synth_rst_clk_wiz_1_150M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_150M_0/ex_synth_rst_clk_wiz_1_150M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_150M_0/ex_synth_rst_clk_wiz_1_150M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_200M_0/ex_synth_rst_clk_wiz_1_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_200M_0/ex_synth_rst_clk_wiz_1_200M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_rst_clk_wiz_1_200M_0/ex_synth_rst_clk_wiz_1_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_0/ex_synth_processor_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_0/ex_synth_processor_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_0/ex_synth_processor_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_axi_intc_0/ex_synth_processor_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_axi_intc_0/ex_synth_processor_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_axi_intc_0/ex_synth_processor_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_dlmb_v10_0/ex_synth_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_dlmb_v10_0/ex_synth_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_ilmb_v10_0/ex_synth_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_ilmb_v10_0/ex_synth_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_dlmb_bram_if_cntlr_0/ex_synth_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_ilmb_bram_if_cntlr_0/ex_synth_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_lmb_bram_0/ex_synth_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_mdm_1_0/ex_synth_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_mdm_1_0/ex_synth_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_xbar_2/ex_synth_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_xbar_3/ex_synth_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_0_0/ex_synth_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_0_0/ex_synth_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_clk_wiz_0_0/ex_synth_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_uartlite_0_0/ex_synth_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_uartlite_0_0/ex_synth_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_uartlite_0_0/ex_synth_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_quad_spi_0_0/ex_synth_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_quad_spi_0_0/ex_synth_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_quad_spi_0_0/ex_synth_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_quad_spi_0_0/ex_synth_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_0/ex_synth_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_0/ex_synth_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_0/ex_synth_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_0/ex_synth_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_0/ex_synth_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_0/ex_synth_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_1/ex_synth_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_1/ex_synth_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_1/ex_synth_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_1/ex_synth_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_1/ex_synth_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_1/ex_synth_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_2/ex_synth_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_2/ex_synth_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_us_2/ex_synth_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_2/ex_synth_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_2/ex_synth_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_2/ex_synth_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_3/ex_synth_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_3/ex_synth_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_3/ex_synth_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_4/ex_synth_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_4/ex_synth_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_4/ex_synth_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_5/ex_synth_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_5/ex_synth_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_5/ex_synth_auto_cc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_6/ex_synth_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_6/ex_synth_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_6/ex_synth_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_7/ex_synth_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_7/ex_synth_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_7/ex_synth_auto_cc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_8/ex_synth_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_8/ex_synth_auto_cc_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_8/ex_synth_auto_cc_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_ethernetlite_0_0/ex_synth_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_ethernetlite_0_0/ex_synth_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_ethernetlite_0_0/ex_synth_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_ethernetlite_0_0/ex_synth_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_timer_0_0/ex_synth_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_axi_timer_0_0/ex_synth_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ex_synth_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_processor_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ex_synth_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ex_synth_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ex_synth_wrapper_utilization_synth.rpt -pb ex_synth_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
