# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3.xci
# IP: The module: 'vcu_DT_blk_design_clk_wiz_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3.xci
# IP: The module: 'vcu_DT_blk_design_clk_wiz_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/xil_logs/vcu118_display_test/vcu118_display_test.srcs/sources_1/bd/vcu_DT_blk_design/ip/vcu_DT_blk_design_clk_wiz_0_3/vcu_DT_blk_design_clk_wiz_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcu_DT_blk_design_clk_wiz_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
