set_property PACKAGE_PIN N30 [get_ports {green[3]}]
set_property PACKAGE_PIN M31 [get_ports {green[2]}]
set_property PACKAGE_PIN P30 [get_ports {green[1]}]
set_property PACKAGE_PIN R29 [get_ports {green[0]}]
set_property PACKAGE_PIN N28 [get_ports {red[3]}]
set_property PACKAGE_PIN P29 [get_ports {red[2]}]
set_property PACKAGE_PIN L31 [get_ports {red[0]}]
set_property PACKAGE_PIN L19 [get_ports reset]

set_property IOSTANDARD LVCMOS18 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports vga_active]
set_property IOSTANDARD LVCMOS18 [get_ports vga_hsync]
set_property IOSTANDARD LVCMOS18 [get_ports vga_vsync]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]




set_property PACKAGE_PIN M30 [get_ports {red[1]}]

set_property PACKAGE_PIN AY14 [get_ports {blue[3]}]
set_property PACKAGE_PIN AV16 [get_ports {blue[2]}]
set_property PACKAGE_PIN AU16 [get_ports {blue[1]}]
set_property PACKAGE_PIN AW15 [get_ports {blue[0]}]
set_property PACKAGE_PIN AY15 [get_ports clk]
set_property PACKAGE_PIN AT15 [get_ports vga_active]
set_property PACKAGE_PIN AV15 [get_ports vga_hsync]
set_property PACKAGE_PIN AT16 [get_ports vga_vsync]
set_property IOSTANDARD DIFF_SSTL12 [get_ports user_si570_clock_clk_p]
