#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 83333000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 83333000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 83333000

/******************************************************************/


/* Definitions for peripheral PROCESSOR_SS_PROCESSOR */
#define XPAR_PROCESSOR_SS_PROCESSOR_ADDR_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_ADDR_TAG_BITS 16
#define XPAR_PROCESSOR_SS_PROCESSOR_ALLOW_DCACHE_WR 1
#define XPAR_PROCESSOR_SS_PROCESSOR_ALLOW_ICACHE_WR 1
#define XPAR_PROCESSOR_SS_PROCESSOR_AREA_OPTIMIZED 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ASYNC_INTERRUPT 1
#define XPAR_PROCESSOR_SS_PROCESSOR_ASYNC_WAKEUP 3
#define XPAR_PROCESSOR_SS_PROCESSOR_AVOID_PRIMITIVES 0
#define XPAR_PROCESSOR_SS_PROCESSOR_BASE_VECTORS 0x0000000000000000
#define XPAR_PROCESSOR_SS_PROCESSOR_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_CACHE_BYTE_SIZE 16384
#define XPAR_PROCESSOR_SS_PROCESSOR_DADDR_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_DATA_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_ADDR_TAG 16
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_ALWAYS_USED 1
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_BASEADDR 0x80000000
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_BYTE_SIZE 16384
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_DATA_WIDTH 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_LINE_LEN 4
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_USE_WRITEBACK 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DCACHE_VICTIMS 8
#define XPAR_PROCESSOR_SS_PROCESSOR_DC_AXI_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_COUNTER_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_ENABLED 1
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_EVENT_COUNTERS 5
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_EXTERNAL_TRACE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_INTERFACE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_LATENCY_COUNTERS 1
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_PROFILE_SIZE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DEBUG_TRACE_SIZE 8192
#define XPAR_PROCESSOR_SS_PROCESSOR_DIV_ZERO_EXCEPTION 1
#define XPAR_PROCESSOR_SS_PROCESSOR_DP_AXI_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_DYNAMIC_BUS_SIZING 0
#define XPAR_PROCESSOR_SS_PROCESSOR_D_AXI 1
#define XPAR_PROCESSOR_SS_PROCESSOR_D_LMB 1
#define XPAR_PROCESSOR_SS_PROCESSOR_D_LMB_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ECC_USE_CE_EXCEPTION 0
#define XPAR_PROCESSOR_SS_PROCESSOR_EDGE_IS_POSITIVE 1
#define XPAR_PROCESSOR_SS_PROCESSOR_ENABLE_DISCRETE_PORTS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ENDIANNESS 1
#define XPAR_PROCESSOR_SS_PROCESSOR_FAULT_TOLERANT 0
#define XPAR_PROCESSOR_SS_PROCESSOR_FPU_EXCEPTION 0
#define XPAR_PROCESSOR_SS_PROCESSOR_FREQ 83333000
#define XPAR_PROCESSOR_SS_PROCESSOR_FSL_EXCEPTION 0
#define XPAR_PROCESSOR_SS_PROCESSOR_FSL_LINKS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_IADDR_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_ALWAYS_USED 1
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_BASEADDR 0x80000000
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_DATA_WIDTH 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_LINE_LEN 8
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_STREAMS 1
#define XPAR_PROCESSOR_SS_PROCESSOR_ICACHE_VICTIMS 8
#define XPAR_PROCESSOR_SS_PROCESSOR_IC_AXI_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_ILL_OPCODE_EXCEPTION 1
#define XPAR_PROCESSOR_SS_PROCESSOR_IMPRECISE_EXCEPTIONS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_INSTR_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_INTERCONNECT 2
#define XPAR_PROCESSOR_SS_PROCESSOR_INTERRUPT_IS_EDGE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_INTERRUPT_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_IP_AXI_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_I_AXI 0
#define XPAR_PROCESSOR_SS_PROCESSOR_I_LMB 1
#define XPAR_PROCESSOR_SS_PROCESSOR_I_LMB_MON 0
#define XPAR_PROCESSOR_SS_PROCESSOR_LMB_DATA_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCKSTEP_MASTER 0
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCKSTEP_SELECT 0
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCKSTEP_SLAVE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_M0_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M0_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M1_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M1_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M2_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M2_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M3_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M3_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M4_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M4_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M5_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M5_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M6_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M6_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M7_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M7_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M8_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M8_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M9_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M9_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M10_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M10_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M11_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M11_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M12_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M12_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M13_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M13_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M14_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M14_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_M15_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M15_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_MMU_DTLB_SIZE 4
#define XPAR_PROCESSOR_SS_PROCESSOR_MMU_ITLB_SIZE 2
#define XPAR_PROCESSOR_SS_PROCESSOR_MMU_PRIVILEGED_INSTR 0
#define XPAR_PROCESSOR_SS_PROCESSOR_MMU_TLB_ACCESS 3
#define XPAR_PROCESSOR_SS_PROCESSOR_MMU_ZONES 2
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_USER_SIGNALS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_USER_VALUE 31
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DP_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_USER_SIGNALS 0
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_USER_VALUE 31
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IP_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_PROCESSOR_SS_PROCESSOR_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_PROCESSOR_SS_PROCESSOR_NUMBER_OF_PC_BRK 1
#define XPAR_PROCESSOR_SS_PROCESSOR_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_PROCESSOR_SS_PROCESSOR_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_PROCESSOR_SS_PROCESSOR_NUM_SYNC_FF_CLK 2
#define XPAR_PROCESSOR_SS_PROCESSOR_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_PROCESSOR_SS_PROCESSOR_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_PROCESSOR_SS_PROCESSOR_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_PROCESSOR_SS_PROCESSOR_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_PROCESSOR_SS_PROCESSOR_OPCODE_0X0_ILLEGAL 1
#define XPAR_PROCESSOR_SS_PROCESSOR_OPTIMIZATION 0
#define XPAR_PROCESSOR_SS_PROCESSOR_PC_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_PIADDR_SIZE 32
#define XPAR_PROCESSOR_SS_PROCESSOR_PVR 2
#define XPAR_PROCESSOR_SS_PROCESSOR_PVR_USER1 0x00
#define XPAR_PROCESSOR_SS_PROCESSOR_PVR_USER2 0x00000000
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR 0x00000000
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_BIP 0
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_DCE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_EE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_EIP 0
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_ICE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_RESET_MSR_IE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_S0_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S0_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S1_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S1_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S2_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S2_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S3_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S3_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S4_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S4_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S5_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S5_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S6_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S6_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S7_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S7_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S8_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S8_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S9_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S9_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S10_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S10_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S11_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S11_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S12_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S12_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S13_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S13_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S14_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S14_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_S15_AXIS_DATA_WIDTH 32
#define XPAR_PROCESSOR_SS_PROCESSOR_S15_AXIS_PROTOCOL GENERIC
#define XPAR_PROCESSOR_SS_PROCESSOR_SCO 0
#define XPAR_PROCESSOR_SS_PROCESSOR_TRACE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_UNALIGNED_EXCEPTIONS 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_BARREL 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_BRANCH_TARGET_CACHE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_CONFIG_RESET 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_DCACHE 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_DIV 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_EXTENDED_FSL_INSTR 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_EXT_BRK 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_EXT_NM_BRK 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_FPU 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_HW_MUL 2
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_ICACHE 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_INTERRUPT 2
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_MMU 3
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_MSR_INSTR 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_NON_SECURE 0
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_PCMP_INSTR 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_REORDER_INSTR 1
#define XPAR_PROCESSOR_SS_PROCESSOR_USE_STACK_PROTECTION 0
#define XPAR_PROCESSOR_SS_PROCESSOR_COMPONENT_NAME ex_synth_processor_0
#define XPAR_PROCESSOR_SS_PROCESSOR_EDK_IPTYPE PROCESSOR
#define XPAR_PROCESSOR_SS_PROCESSOR_EDK_SPECIAL microblaze
#define XPAR_PROCESSOR_SS_PROCESSOR_G_TEMPLATE_LIST 4
#define XPAR_PROCESSOR_SS_PROCESSOR_G_USE_EXCEPTIONS 1

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 16
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 16384
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 16
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 16384
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 8
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 1
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 83333000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0xBFFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 8
#define XPAR_MICROBLAZE_ICACHE_STREAMS 1
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 8
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 1
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 2
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 1
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 1
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 2
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 1
#define XPAR_MICROBLAZE_USE_BARREL 1
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 1
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 2
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 3
#define XPAR_MICROBLAZE_USE_MSR_INSTR 1
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 1
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME ex_synth_processor_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 4
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 1

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_MB
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 2U

/* Definitions for peripheral PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x00001FFFU
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 1U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x00001FFFU
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_0_WRITE_ACCESS 2U
#define XPAR_BRAM_0_BASEADDR 0x00000000U
#define XPAR_BRAM_0_HIGHADDR 0x00001FFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_PROCESSOR_SS_PROCESSOR_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x00001FFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver EMACLITE */
#define XPAR_XEMACLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_ETHERNETLITE_0 */
#define XPAR_AXI_ETHERNETLITE_0_DEVICE_ID 0
#define XPAR_AXI_ETHERNETLITE_0_BASEADDR 0x40E00000
#define XPAR_AXI_ETHERNETLITE_0_HIGHADDR 0x40E0FFFF
#define XPAR_AXI_ETHERNETLITE_0_TX_PING_PONG 1
#define XPAR_AXI_ETHERNETLITE_0_RX_PING_PONG 1
#define XPAR_AXI_ETHERNETLITE_0_INCLUDE_MDIO 1
#define XPAR_AXI_ETHERNETLITE_0_INCLUDE_INTERNAL_LOOPBACK 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_ETHERNETLITE_0 */
#define XPAR_EMACLITE_0_DEVICE_ID XPAR_AXI_ETHERNETLITE_0_DEVICE_ID
#define XPAR_EMACLITE_0_BASEADDR 0x40E00000
#define XPAR_EMACLITE_0_HIGHADDR 0x40E0FFFF
#define XPAR_EMACLITE_0_TX_PING_PONG 1
#define XPAR_EMACLITE_0_RX_PING_PONG 1
#define XPAR_EMACLITE_0_INCLUDE_MDIO 1
#define XPAR_EMACLITE_0_INCLUDE_INTERNAL_LOOPBACK 0


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral HLS_IP_RESET */
#define XPAR_HLS_IP_RESET_BASEADDR 0x40010000
#define XPAR_HLS_IP_RESET_HIGHADDR 0x4001FFFF
#define XPAR_HLS_IP_RESET_DEVICE_ID 0
#define XPAR_HLS_IP_RESET_INTERRUPT_PRESENT 0
#define XPAR_HLS_IP_RESET_IS_DUAL 0


/* Definitions for peripheral VIDEO_LOCK_MONITOR */
#define XPAR_VIDEO_LOCK_MONITOR_BASEADDR 0x40000000
#define XPAR_VIDEO_LOCK_MONITOR_HIGHADDR 0x4000FFFF
#define XPAR_VIDEO_LOCK_MONITOR_DEVICE_ID 1
#define XPAR_VIDEO_LOCK_MONITOR_INTERRUPT_PRESENT 0
#define XPAR_VIDEO_LOCK_MONITOR_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral HLS_IP_RESET */
#define XPAR_GPIO_0_BASEADDR 0x40010000
#define XPAR_GPIO_0_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_HLS_IP_RESET_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral VIDEO_LOCK_MONITOR */
#define XPAR_GPIO_1_BASEADDR 0x40000000
#define XPAR_GPIO_1_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_VIDEO_LOCK_MONITOR_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 3
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral PROCESSOR_SS_PROCESSOR_AXI_INTC */
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_DEVICE_ID 0
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_BASEADDR 0x41200000
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_KIND_OF_INTR 0xFFFFFFFE
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_HAS_FAST 1
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_NUM_INTR_INPUTS 3
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_DEVICE_ID
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_TYPE 0U
#define XPAR_V_FRMBUF_RD_0_INTERRUPT_MASK 0X000001U
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_V_FRMBUF_RD_0_INTERRUPT_INTR 0U
#define XPAR_AXI_QUAD_SPI_0_IP2INTC_IRPT_MASK 0X000002U
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_AXI_QUAD_SPI_0_IP2INTC_IRPT_INTR 1U
#define XPAR_AXI_UARTLITE_0_INTERRUPT_MASK 0X000004U
#define XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR 2U

/******************************************************************/

/* Canonical definitions for peripheral PROCESSOR_SS_PROCESSOR_AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000U
#define XPAR_INTC_0_HIGHADDR 0x4120FFFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFEU
#define XPAR_INTC_0_HAS_FAST 1U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 3U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_V_FRMBUF_RD_0_VEC_ID XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_V_FRMBUF_RD_0_INTERRUPT_INTR
#define XPAR_INTC_0_SPI_0_VEC_ID XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_AXI_QUAD_SPI_0_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTLITE_0_VEC_ID XPAR_PROCESSOR_SS_PROCESSOR_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver MIG_7SERIES */
#define XPAR_XMIG7SERIES_NUM_INSTANCES 1U

/* Definitions for peripheral MEMORY_SS_MIG */
#define XPAR_MEMORY_SS_MIG_DEVICE_ID 0U
#define XPAR_MEMORY_SS_MIG_DDR3_ROW_WIDTH 14U
#define XPAR_MEMORY_SS_MIG_DDR3_COL_WIDTH 0U
#define XPAR_MEMORY_SS_MIG_DDR3_BANK_WIDTH 3U
#define XPAR_MEMORY_SS_MIG_DDR3_DQ_WIDTH 16U


/******************************************************************/


/* Definitions for peripheral MEMORY_SS_MIG */
#define XPAR_MEMORY_SS_MIG_BASEADDR 0x80000000
#define XPAR_MEMORY_SS_MIG_HIGHADDR 0xBFFFFFFF


/******************************************************************/

/* Canonical definitions for peripheral MEMORY_SS_MIG */
#define XPAR_MIG7SERIES_0_DEVICE_ID XPAR_MEMORY_SS_MIG_DEVICE_ID
#define XPAR_MIG7SERIES_0_DDR_ROW_WIDTH 14U
#define XPAR_MIG7SERIES_0_DDR_COL_WIDTH 0U
#define XPAR_MIG7SERIES_0_DDR_BANK_WIDTH 3U
#define XPAR_MIG7SERIES_0_DDR_DQ_WIDTH 16U
#define XPAR_MIG7SERIES_0_BASEADDR 0x80000000U
#define XPAR_MIG7SERIES_0_HIGHADDR 0xBFFFFFFFU


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_DEVICE_ID 0U
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44A20000U
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44A2FFFFU
#define XPAR_AXI_QUAD_SPI_0_FIFO_DEPTH 16U
#define XPAR_AXI_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_AXI_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 1U
#define XPAR_AXI_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 2U
#define XPAR_AXI_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_BASEADDR 0U
#define XPAR_AXI_QUAD_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x44A20000U
#define XPAR_SPI_0_HIGHADDR 0x44A2FFFFU
#define XPAR_SPI_0_FIFO_DEPTH 16U
#define XPAR_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 1U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_0_SPI_MODE 2U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 0U
#define XPAR_SPI_0_AXI4_BASEADDR 0U
#define XPAR_SPI_0_AXI4_HIGHADDR 0U
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_DEVICE_ID 0U
#define XPAR_AXI_TIMER_0_BASEADDR 0x41C00000U
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41C0FFFFU
#define XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ 83333000U


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000U
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060FFFF
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0
#define XPAR_AXI_UARTLITE_0_BAUDRATE 9600
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8


/******************************************************************/

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_AXI_UARTLITE_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFF
#define XPAR_UARTLITE_0_BAUDRATE 9600
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 8


/******************************************************************/

/* Definitions for driver V_FRMBUF_RD */
#define XPAR_XV_FRMBUFRD_NUM_INSTANCES 1

/* Definitions for peripheral V_FRMBUF_RD_0 */
#define XPAR_V_FRMBUF_RD_0_DEVICE_ID 0
#define XPAR_V_FRMBUF_RD_0_S_AXI_CTRL_BASEADDR 0x44A10000
#define XPAR_V_FRMBUF_RD_0_S_AXI_CTRL_HIGHADDR 0x44A1FFFF
#define XPAR_V_FRMBUF_RD_0_SAMPLES_PER_CLOCK 1
#define XPAR_V_FRMBUF_RD_0_MAX_COLS 1057
#define XPAR_V_FRMBUF_RD_0_MAX_ROWS 629
#define XPAR_V_FRMBUF_RD_0_MAX_DATA_WIDTH 8
#define XPAR_V_FRMBUF_RD_0_AXIMM_DATA_WIDTH 64
#define XPAR_V_FRMBUF_RD_0_AXIMM_ADDR_WIDTH 32
#define XPAR_V_FRMBUF_RD_0_HAS_RGBX8 1
#define XPAR_V_FRMBUF_RD_0_HAS_YUVX8 1
#define XPAR_V_FRMBUF_RD_0_HAS_YUYV8 1
#define XPAR_V_FRMBUF_RD_0_HAS_RGBA8 0
#define XPAR_V_FRMBUF_RD_0_HAS_YUVA8 0
#define XPAR_V_FRMBUF_RD_0_HAS_RGBX10 0
#define XPAR_V_FRMBUF_RD_0_HAS_YUVX10 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV8 1
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV8_420 1
#define XPAR_V_FRMBUF_RD_0_HAS_RGB8 1
#define XPAR_V_FRMBUF_RD_0_HAS_YUV8 1
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV10 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV10_420 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y8 1
#define XPAR_V_FRMBUF_RD_0_HAS_Y10 0
#define XPAR_V_FRMBUF_RD_0_HAS_BGRA8 0
#define XPAR_V_FRMBUF_RD_0_HAS_BGRX8 1
#define XPAR_V_FRMBUF_RD_0_HAS_UYVY8 1
#define XPAR_V_FRMBUF_RD_0_HAS_BGR8 1
#define XPAR_V_FRMBUF_RD_0_HAS_RGBX12 0
#define XPAR_V_FRMBUF_RD_0_HAS_RGB16 0
#define XPAR_V_FRMBUF_RD_0_HAS_YUVX12 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV12 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV12_420 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y12 0
#define XPAR_V_FRMBUF_RD_0_HAS_YUV16 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV16 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y_UV16_420 0
#define XPAR_V_FRMBUF_RD_0_HAS_Y16 0
#define XPAR_V_FRMBUF_RD_0_HAS_INTERLACED 0


/******************************************************************/

/* Canonical definitions for peripheral V_FRMBUF_RD_0 */
#define XPAR_XV_FRMBUFRD_0_DEVICE_ID XPAR_V_FRMBUF_RD_0_DEVICE_ID
#define XPAR_XV_FRMBUFRD_0_S_AXI_CTRL_BASEADDR 0x44A10000
#define XPAR_XV_FRMBUFRD_0_S_AXI_CTRL_HIGHADDR 0x44A1FFFF
#define XPAR_XV_FRMBUFRD_0_SAMPLES_PER_CLOCK 1
#define XPAR_XV_FRMBUFRD_0_MAX_COLS 1057
#define XPAR_XV_FRMBUFRD_0_MAX_ROWS 629
#define XPAR_XV_FRMBUFRD_0_MAX_DATA_WIDTH 8
#define XPAR_XV_FRMBUFRD_0_AXIMM_DATA_WIDTH 64
#define XPAR_XV_FRMBUFRD_0_AXIMM_ADDR_WIDTH 32
#define XPAR_XV_FRMBUFRD_0_HAS_RGBX8 1
#define XPAR_XV_FRMBUFRD_0_HAS_YUVX8 1
#define XPAR_XV_FRMBUFRD_0_HAS_YUYV8 1
#define XPAR_XV_FRMBUFRD_0_HAS_RGBA8 0
#define XPAR_XV_FRMBUFRD_0_HAS_YUVA8 0
#define XPAR_XV_FRMBUFRD_0_HAS_RGBX10 0
#define XPAR_XV_FRMBUFRD_0_HAS_YUVX10 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV8 1
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV8_420 1
#define XPAR_XV_FRMBUFRD_0_HAS_RGB8 1
#define XPAR_XV_FRMBUFRD_0_HAS_YUV8 1
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV10 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV10_420 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y8 1
#define XPAR_XV_FRMBUFRD_0_HAS_Y10 0
#define XPAR_XV_FRMBUFRD_0_HAS_BGRA8 0
#define XPAR_XV_FRMBUFRD_0_HAS_BGRX8 1
#define XPAR_XV_FRMBUFRD_0_HAS_UYVY8 1
#define XPAR_XV_FRMBUFRD_0_HAS_BGR8 1
#define XPAR_XV_FRMBUFRD_0_HAS_RGBX12 0
#define XPAR_XV_FRMBUFRD_0_HAS_RGB16 0
#define XPAR_XV_FRMBUFRD_0_HAS_YUVX12 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV12 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV12_420 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y12 0
#define XPAR_XV_FRMBUFRD_0_HAS_YUV16 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV16 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y_UV16_420 0
#define XPAR_XV_FRMBUFRD_0_HAS_Y16 0
#define XPAR_XV_FRMBUFRD_0_HAS_INTERLACED 0


/******************************************************************/

/* Definitions for driver VTC */
#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral V_TC_0 */
#define XPAR_V_TC_0_DEVICE_ID 0
#define XPAR_V_TC_0_BASEADDR 0x44A00000
#define XPAR_V_TC_0_HIGHADDR 0x44A0FFFF
#define XPAR_V_TC_0_GENERATE_EN 1
#define XPAR_V_TC_0_DETECT_EN 0
#define XPAR_V_TC_0_DET_HSYNC_EN 1
#define XPAR_V_TC_0_DET_VSYNC_EN 1
#define XPAR_V_TC_0_DET_HBLANK_EN 1
#define XPAR_V_TC_0_DET_VBLANK_EN 1
#define XPAR_V_TC_0_DET_AVIDEO_EN 1
#define XPAR_V_TC_0_DET_ACHROMA_EN 0


/******************************************************************/

/* Canonical definitions for peripheral V_TC_0 */
#define XPAR_VTC_0_DEVICE_ID XPAR_V_TC_0_DEVICE_ID
#define XPAR_VTC_0_BASEADDR 0x44A00000
#define XPAR_VTC_0_HIGHADDR 0x44A0FFFF
#define XPAR_VTC_0_GENERATE_EN 1
#define XPAR_VTC_0_DETECT_EN 0
#define XPAR_VTC_0_DET_HSYNC_EN 1
#define XPAR_VTC_0_DET_VSYNC_EN 1
#define XPAR_VTC_0_DET_HBLANK_EN 1
#define XPAR_VTC_0_DET_VBLANK_EN 1
#define XPAR_VTC_0_DET_AVIDEO_EN 1
#define XPAR_VTC_0_DET_ACHROMA_EN 0


/******************************************************************/

#endif  /* end of protection macro */
