# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9.xci
# IP: The module: 'ex_synth_auto_cc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_auto_cc_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_auto_cc_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9.xci
# IP: The module: 'ex_synth_auto_cc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_auto_cc_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rwegter/vivado_projects/v_frmbuf_rd_2_ex/v_frmbuf_rd_2_ex.srcs/sources_1/bd/ex_synth/ip/ex_synth_auto_cc_9/ex_synth_auto_cc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex_synth_auto_cc_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
