webtalk_init -webtalk_dir /home/rwegter/ECE-Capstone-proj-7/vivado_projects/frbuf_rd_test/frbuf_rd_test.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-04-26 13:51:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211633569_1777539552_210695033_346" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i1jv6ocgicv6afkasfrpm34e4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2393.405 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.264 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1619469973000" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key Device -value "7a35ti" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1619469973000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key DebugCount -value "4" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1619470312657"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1619470312657"
webtalk_transmit -clientid 1336493600 -regid "211633569_1777539552_210695033_346" -xml /home/rwegter/ECE-Capstone-proj-7/vivado_projects/frbuf_rd_test/frbuf_rd_test.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/rwegter/ECE-Capstone-proj-7/vivado_projects/frbuf_rd_test/frbuf_rd_test.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/rwegter/ECE-Capstone-proj-7/vivado_projects/frbuf_rd_test/frbuf_rd_test.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
